// Cmod A7-35T RISC-V MCU — unified datasheet template.
// body.typ and meta.typ are generated by build_datasheet.py; the markdown
// files under docs/ remain the single source of truth.
#import "defs.typ": *
#import "meta.typ": *

#set text(font: ("Liberation Sans", "DejaVu Sans"), size: 9pt)
#set par(justify: true, leading: 0.55em)
#set heading(numbering: "1.1")

#set page(
  paper: "a4",
  margin: (top: 2.2cm, bottom: 2.1cm, x: 1.5cm),
  header: context {
    if counter(page).get().first() > 1 {
      grid(
        columns: (1fr, auto),
        align: (left + bottom, right + bottom),
        text(weight: "bold", size: 11.5pt)[RISC-V MCU on Cmod A7-35T],
        text(size: 8pt, fill: luma(90))[Datasheet & Reference Manual],
      )
      v(-0.5em)
      line(length: 100%, stroke: 1.2pt)
    }
  },
  footer: context {
    line(length: 100%, stroke: 0.6pt)
    v(-0.4em)
    grid(
      columns: (1fr, 1fr, 1fr),
      align: (left, center, right),
      text(size: 7.5pt)[© 2026 NCKU MPPA Course],
      text(size: 8pt, style: "italic", fill: luma(110))[Preliminary],
      text(size: 7.5pt)[DS-CMOD7-0001 · page #counter(page).display() of #counter(page).final().first()],
    )
  },
)

#show heading.where(level: 1): it => {
  pagebreak(weak: true)
  block(above: 0.4em, below: 1.1em, text(size: 16pt, it))
}
#show heading.where(level: 2): it => {
  block(above: 1.5em, below: 0.7em, sticky: true, text(size: 12pt, it))
}
#show heading.where(level: 3): it => {
  block(above: 1.2em, below: 0.6em, sticky: true, text(size: 10.5pt, it))
}
#show heading.where(level: 4): it => {
  block(above: 1.0em, below: 0.5em, sticky: true, text(size: 9.5pt, it))
}

#set table(stroke: 0.4pt + luma(140), inset: 4.5pt,
  fill: (x, y) => if y == 0 { luma(233) })
#show table: set text(size: 8pt)
#show figure.caption: set text(size: 8pt, style: "italic")
#show raw.where(block: true): it => block(
  width: 100%, fill: luma(246), inset: 8pt, radius: 2pt,
  stroke: 0.4pt + luma(200), breakable: false, text(size: 8pt, it))

// ---------------- title page ----------------
#text(size: 9pt, tracking: 0.08em, fill: luma(70))[NCKU · MICROPROCESSOR PRINCIPLES AND APPLICATIONS]
#v(-0.5em)
#line(length: 100%, stroke: 2pt)
#v(2.2cm)
#par(justify: false)[#text(size: 26pt, weight: "bold", hyphenate: false)[Cmod A7-35T RISC-V MCU]]
#v(0.2em)
#text(size: 14pt, fill: luma(60))[Datasheet & Reference Manual]
#v(0.4em)
#text(size: 10.5pt, fill: luma(90))[MicroBlaze-V soft MCU on the Digilent Cmod A7-35T — peripherals, pins, power, and boot guides]
#v(1.4cm)
#table(
  columns: (auto, 1fr), stroke: none, inset: (y: 4pt), fill: none,
  [*Platform*], [#meta-platform],
  [*Processor*], [#meta-processor],
  [*Toolchain*], [#meta-toolchain],
)
#v(0.6cm)
#text(size: 9pt, fill: luma(90))[Document DS-CMOD7-0001 · Revision A · July 2026]
#v(1.2cm)
#outline(title: [Table of Contents], depth: 3)

// ---------------- body (generated from markdown) ----------------
#include "body.typ"
